/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HumanCheckpointRouteImport } from './routes/human-checkpoint'
import { Route as IndexRouteImport } from './routes/index'

const HumanCheckpointRoute = HumanCheckpointRouteImport.update({
  id: '/human-checkpoint',
  path: '/human-checkpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/human-checkpoint': typeof HumanCheckpointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/human-checkpoint': typeof HumanCheckpointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/human-checkpoint': typeof HumanCheckpointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/human-checkpoint'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/human-checkpoint'
  id: '__root__' | '/' | '/human-checkpoint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HumanCheckpointRoute: typeof HumanCheckpointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/human-checkpoint': {
      id: '/human-checkpoint'
      path: '/human-checkpoint'
      fullPath: '/human-checkpoint'
      preLoaderRoute: typeof HumanCheckpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HumanCheckpointRoute: HumanCheckpointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
